// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: usage.proto

package Usage;

public interface AverageResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartEnergy.AverageResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code> string avgRes = 1; </code>
     */
    String getAvgRes();

    /**
     * <code> string avgRes = 1; </code>
     */
    com.google.protobuf.ByteString
    getAvgResBytes();
}
