// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: usage.proto

package Usage;

public interface AverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartEnergy.AverageRequest)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code> double avgReq = 1;</code>
         */
        double getAvgReq();
    }
