// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: usage.proto

package Usage;

public class UsageImpl {

    private UsageImpl() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartEnergy_AverageRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartEnergy_AverageRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartEnergy_AverageResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartEnergy_AverageResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016index.proto\022\010SmartEnergy\"\036\n\rAverageRequ" +
                        "est\022\r\n\005AvgReq\030\001 \001(\001\"!\n\016AverageResponse\022\017\n\007" +
                        "total\030\001 \001(\t2S\n\013Usage\022D\n\013Usage" +
                        "\022\027.SmartEnergy.AverageRequest\032\030.SmartEnergy." +
                        "AverageResponse(\0010\001B\035\n\013UsageB\014Usage" +
                        "ImplP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SmartEnergy_AverageRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SmartEnergy_AverageRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartEnergy_AverageRequest_descriptor,
                new java.lang.String[] { "AvgReq", });
        internal_static_SmartEnergy_AverageResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_SmartEnergy_AverageResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartEnergy_AverageResponse_descriptor,
                new java.lang.String[] { "AvgRes", });
    }
    // @@protoc_insertion_point(outer_class_scope)
}
