// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: heater.proto

package Heater;

public final class HeaterServiceImpl {
    public HeaterServiceImpl() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartEnergy_TemperatureRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartEnergy_TemperatureRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartEnergy_TemperatureResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartEnergy_TemperatureResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016heater.proto\022\010SmartEnergy\"\021\n\017TemperatureRe" +
                        "quest\"*\n\017TemperatureResponse\022\027\n\017heatingOff" +
                        "\030\001 \001(\t2W\n\010HeaterService\022K\n\021Heater" +
                        "\022\031.SmartEnergy.TemperatureRequest\032\031.SmartEnergy" +
                        ".TemperatureResponse\"\000B\035\n\013HeaterB\014HeaterServi" +
                        "ceImplP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };

        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SmartEnergy_TemperatureRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SmartEnergy_TemperatureRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartEnergy_TemperatureRequest_descriptor,
                new java.lang.String[] { "Text", });
        internal_static_SmartEnergy_TemperatureResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_SmartEnergy_TemperatureResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartEnergy_TemperatureResponse_descriptor,
                new java.lang.String[] { "Length", });
    }
    // @@protoc_insertion_point(outer_class_scope)
}
