// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: heater.proto

package Heater;

public interface TemperatureResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Heater.TemperatureResponse)
        com.google.protobuf.MessageOrBuilder {

    java.lang.String getHeatingOff();
    /**
     * <code> string heatingOff = 1;</code>
     */
    com.google.protobuf.ByteString
    getHeatingOffBytes();

    // Method getLength
    int getLength();
}
