// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: heater.proto

package Heater;

public interface TemperatureRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartEnergy.TemperatureRequest)
        com.google.protobuf.MessageOrBuilder {
}