// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: setting.proto

package Setting;

public final class SettingServiceImpl {
        private SettingServiceImpl() {}
        public static void registerAllExtensions(
                com.google.protobuf.ExtensionRegistryLite registry) {
        }

        public static void registerAllExtensions(
                com.google.protobuf.ExtensionRegistry registry) {
            registerAllExtensions(
                    (com.google.protobuf.ExtensionRegistryLite) registry);
        }
        static final com.google.protobuf.Descriptors.Descriptor
                internal_static_SmartEnergy_TempReadRequest_descriptor;
        static final
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internal_static_SmartEnergy_TempReadRequest_fieldAccessorTable;
        static final com.google.protobuf.Descriptors.Descriptor
                internal_static_SmartEnergy_TempSetResponse_descriptor;
        static final
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internal_static_SmartEnergy_TempSetResponse_fieldAccessorTable;

        public static com.google.protobuf.Descriptors.FileDescriptor
        getDescriptor() {
            return descriptor;
        }
        private static  com.google.protobuf.Descriptors.FileDescriptor
                descriptor;
        static {
            java.lang.String[] descriptorData = {
                    "\n\016setting.proto\022\010SmartEnergy\")\n\023TempRead" +
                            "Request\022\022\n\ntempReading\030\001 \001(\005\"(\n\024TempSet" +
                            "Response\022\020\n\010newSetPoint\030\001 \001(\0012_\n\014Setting" +
                            "\022O\n\014SetTemperature\022\035.SmartEnergy.TempRead" +
                            "Request\032\036.SmartEnergy.TempSetResponse" +
                            "(\001B\036\n\014SettingServiceB\014SettingServiceImplP\001" +
                            "b\006proto3"
            };
            com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                    new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                        public com.google.protobuf.ExtensionRegistry assignDescriptors(
                                com.google.protobuf.Descriptors.FileDescriptor root) {
                            descriptor = root;
                            return null;
                        }
                    };
            com.google.protobuf.Descriptors.FileDescriptor
                    .internalBuildGeneratedFileFrom(descriptorData,
                            new com.google.protobuf.Descriptors.FileDescriptor[] {
                            }, assigner);
            internal_static_SmartEnergy_TempReadRequest_descriptor =
                    getDescriptor().getMessageTypes().get(0);
            internal_static_SmartEnergy_TempReadRequest_fieldAccessorTable = new
                    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                    internal_static_SmartEnergy_TempReadRequest_descriptor,
                    new java.lang.String[] { "tempReading", });
            internal_static_SmartEnergy_TempSetResponse_descriptor =
                    getDescriptor().getMessageTypes().get(1);
            internal_static_SmartEnergy_TempSetResponse_fieldAccessorTable = new
                    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                    internal_static_SmartEnergy_TempSetResponse_descriptor,
                    new java.lang.String[] { "newSetPoint", });
        }
        // @@protoc_insertion_point(outer_class_scope)
    }

