// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: setting.proto

package Setting;

public interface TempReadRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartEnergy.TempReadRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code> double tempReading = 1;</code>
     */
    double getTempReading();
}
