// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: setting.proto

package Setting;

public interface TempSetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartEnergy.TempSetResponse)
    com.google.protobuf.MessageOrBuilder {

        /**
         * <code> double newSetPoint  = 1;</code>
         */
        double getNewSetPoint();
    }
