// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: temperature.proto

package Temperature;


public final class TemperatureServiceImpl {

    public TemperatureServiceImpl() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartEnergy_TempStatusRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartEnergy_TempStatusRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartEnergy_TempStatusResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartEnergy_TempStatusResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016temperature.proto\022\010SmartEnergy\"\n\030TempStatus" +
                        "Request\022\017\n\007tempStatus\030\001 \001\005\022\023\n\t " +
                        "TempStatusResponse\022\r\n\005tempCurr\030\001 \001" +
                        "(\0012_\n\rTemperature\022N\n\rTemperature\022\".Smart" +
                        "Energy.TempStatusRequest\032\027.SmartEnergy" +
                        ".TempStatusResponse0\001B\037\n\rTemperatureServiceB\014" +
                        "TemperatureSeviceImplP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SmartEnergy_TempStatusRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SmartEnergy_TempStatusRequest_fieldAccessorTable  = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartEnergy_TempStatusRequest_descriptor,
                new java.lang.String[] { "tempStatus"});
        internal_static_SmartEnergy_TempStatusResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_SmartEnergy_TempStatusResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartEnergy_TempStatusResponse_descriptor,
                new java.lang.String[] { "tempCurr", });
    }
    // @@protoc_insertion_point(outer_class_scope)
}
