// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: temperature.proto

package Temperature;

public interface TempStatusRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartEnergy.TempStatusRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code> int32 tempStatus = 1;</code>
     */
    int getTempStatus();
}
