// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: temperature.proto

package Temperature;

    public interface TempStatusResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SmartEnergy.TempStatusResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code> double tempCurr = 1;</code>
         */
        double tempCurr();
    }

